# Generated by Django 4.2.16 on 2024-10-29 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('create_at', models.DateField()),
                ('image', models.ImageField(upload_to='static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=50)),
                ('speed', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('probeg', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carcompany.company')),
            ],
        ),
    ]
